common:
    output_path: /ossfs/workspace/output
    log_path: /ossfs/workspace/logs
    save_per_iters: 3000
    use_bf16: 1
    use_fp16: 0
    use_fsdp: 1
    use_zero: 0
    random_seed: 1024
    log_interval: 1
    machines: 1
    task: 't2i'

optimize:
    max_epochs: 6
    warmup_epochs: 0.1
    lr: 2.0e-5
    lr_scheduler: 'cosine'
    optimizer: 'adamw'
    weight_decay: 0.05
    betas: [0.9, 0.95]
    eps: 1.0e-06

model:
    model_path: /mnt/prev_nas/refine_draw/models/deepseek-ai/Janus-Pro-7B
    processor_path: /mnt/prev_nas/refine_draw/models/deepseek-ai/Janus-Pro-7B

dataloader:
    num_workers: 4
    prefetch_factor: 4
    sampler_shuffle: False
    train:
        batch_size: 4

        